# -*- coding: utf-8 -*-
"""
Listado MANUAL de todas las cartas del Santuario Arcano.

Esta es una lista plana y editable a mano: agrega, borra o modifica
entradas de CARDS libremente. No hay ninguna función que invente o
genere cartas automáticamente; todo lo que está aquí es literal.

Cada carta es un dict con:
  id         -> entero único (no lo repitas entre cartas)
  name       -> nombre que se muestra
  rarity     -> "comun" | "rara" | "epica" | "legendaria"
  categorias -> LISTA de textos libres (ej. ["Fuego", "Bestia"]).
                Una carta puede tener una o varias. Se muestran junto
                a la rareza, y se pueden usar para filtrar en Colección.
  image      -> nombre del archivo .png dentro de static/images/cards/
  flavor     -> breve descripción/lore. Se muestra en la carta y su ficha.

No hay campo de emoji/icono: si una carta todavía no tiene imagen, se
muestran automáticamente las iniciales de su nombre en su lugar.
"""

CARDS = [
    {
        "id": 1,
        "name": "Salamandra Joven",
        "rarity": "comun",
        "categorias": ["Fuego"],
        "image": "001.png",
        "flavor": "Un ejemplar joven de salamandra, apenas consciente de la fuerza del fuego que corre por sus venas.",
    },
    {
        "id": 2,
        "name": "Salamandra Salvaje",
        "rarity": "comun",
        "categorias": ["Fuego"],
        "image": "002.png",
        "flavor": "Un salamandra salvaje que vaga sin rumbo, atraído instintivamente por cualquier foco de energía de fuego.",
    },
    {
        "id": 3,
        "name": "Salamandra Errante",
        "rarity": "comun",
        "categorias": ["Fuego"],
        "image": "003.png",
        "flavor": "Un salamandra errante, expulsado de su manada por no lograr aún controlar su afinidad con el fuego.",
    },
    {
        "id": 4,
        "name": "Sirénido Joven",
        "rarity": "comun",
        "categorias": ["Agua"],
        "image": "004.png",
        "flavor": "Un ejemplar joven de sirénido, apenas consciente de la fuerza del agua que corre por sus venas.",
    },
    {
        "id": 5,
        "name": "Sirénido Salvaje",
        "rarity": "comun",
        "categorias": ["Agua"],
        "image": "005.png",
        "flavor": "Un sirénido salvaje que vaga sin rumbo, atraído instintivamente por cualquier foco de energía de agua.",
    },
    {
        "id": 6,
        "name": "Sirénido Errante",
        "rarity": "comun",
        "categorias": ["Agua"],
        "image": "006.png",
        "flavor": "Un sirénido errante, expulsado de su manada por no lograr aún controlar su afinidad con el agua.",
    },
    {
        "id": 7,
        "name": "Coloso Joven",
        "rarity": "comun",
        "categorias": ["Tierra"],
        "image": "007.png",
        "flavor": "Un ejemplar joven de coloso, apenas consciente de la fuerza de la tierra que corre por sus venas.",
    },
    {
        "id": 8,
        "name": "Coloso Salvaje",
        "rarity": "comun",
        "categorias": ["Tierra"],
        "image": "008.png",
        "flavor": "Un coloso salvaje que vaga sin rumbo, atraído instintivamente por cualquier foco de energía de tierra.",
    },
    {
        "id": 9,
        "name": "Coloso Errante",
        "rarity": "comun",
        "categorias": ["Tierra"],
        "image": "009.png",
        "flavor": "Un coloso errante, expulsado de su manada por no lograr aún controlar su afinidad con la tierra.",
    },
    {
        "id": 10,
        "name": "Grifón Joven",
        "rarity": "comun",
        "categorias": ["Aire"],
        "image": "010.png",
        "flavor": "Un ejemplar joven de grifón, apenas consciente de la fuerza del aire que corre por sus venas.",
    },
    {
        "id": 11,
        "name": "Grifón Salvaje",
        "rarity": "comun",
        "categorias": ["Aire"],
        "image": "011.png",
        "flavor": "Un grifón salvaje que vaga sin rumbo, atraído instintivamente por cualquier foco de energía de aire.",
    },
    {
        "id": 12,
        "name": "Grifón Errante",
        "rarity": "comun",
        "categorias": ["Aire"],
        "image": "012.png",
        "flavor": "Un grifón errante, expulsado de su manada por no lograr aún controlar su afinidad con el aire.",
    },
    {
        "id": 13,
        "name": "Tronante Joven",
        "rarity": "comun",
        "categorias": ["Rayo"],
        "image": "013.png",
        "flavor": "Un ejemplar joven de tronante, apenas consciente de la fuerza del rayo que corre por sus venas.",
    },
    {
        "id": 14,
        "name": "Tronante Salvaje",
        "rarity": "comun",
        "categorias": ["Rayo"],
        "image": "014.png",
        "flavor": "Un tronante salvaje que vaga sin rumbo, atraído instintivamente por cualquier foco de energía de rayo.",
    },
    {
        "id": 15,
        "name": "Tronante Errante",
        "rarity": "comun",
        "categorias": ["Rayo"],
        "image": "015.png",
        "flavor": "Un tronante errante, expulsado de su manada por no lograr aún controlar su afinidad con el rayo.",
    },
    {
        "id": 16,
        "name": "Espectro Joven",
        "rarity": "comun",
        "categorias": ["Sombra"],
        "image": "016.png",
        "flavor": "Un ejemplar joven de espectro, apenas consciente de la fuerza de la sombra que corre por sus venas.",
    },
    {
        "id": 17,
        "name": "Espectro Salvaje",
        "rarity": "comun",
        "categorias": ["Sombra"],
        "image": "017.png",
        "flavor": "Un espectro salvaje que vaga sin rumbo, atraído instintivamente por cualquier foco de energía de sombra.",
    },
    {
        "id": 18,
        "name": "Espectro Errante",
        "rarity": "comun",
        "categorias": ["Sombra"],
        "image": "018.png",
        "flavor": "Un espectro errante, expulsado de su manada por no lograr aún controlar su afinidad con la sombra.",
    },
    {
        "id": 19,
        "name": "Vigía Joven",
        "rarity": "comun",
        "categorias": ["Luz"],
        "image": "019.png",
        "flavor": "Un ejemplar joven de vigía, apenas consciente de la fuerza de la luz que corre por sus venas.",
    },
    {
        "id": 20,
        "name": "Vigía Salvaje",
        "rarity": "comun",
        "categorias": ["Luz"],
        "image": "020.png",
        "flavor": "Un vigía salvaje que vaga sin rumbo, atraído instintivamente por cualquier foco de energía de luz.",
    },
    {
        "id": 21,
        "name": "Vigía Errante",
        "rarity": "comun",
        "categorias": ["Luz"],
        "image": "021.png",
        "flavor": "Un vigía errante, expulsado de su manada por no lograr aún controlar su afinidad con la luz.",
    },
    {
        "id": 22,
        "name": "Autómata Joven",
        "rarity": "comun",
        "categorias": ["Arcano"],
        "image": "022.png",
        "flavor": "Un ejemplar joven de autómata, apenas consciente de la fuerza del arcano que corre por sus venas.",
    },
    {
        "id": 23,
        "name": "Autómata Salvaje",
        "rarity": "comun",
        "categorias": ["Arcano"],
        "image": "023.png",
        "flavor": "Un autómata salvaje que vaga sin rumbo, atraído instintivamente por cualquier foco de energía de arcano.",
    },
    {
        "id": 24,
        "name": "Autómata Errante",
        "rarity": "comun",
        "categorias": ["Arcano"],
        "image": "024.png",
        "flavor": "Un autómata errante, expulsado de su manada por no lograr aún controlar su afinidad con el arcano.",
    },
    {
        "id": 25,
        "name": "Dríada Joven",
        "rarity": "comun",
        "categorias": ["Naturaleza"],
        "image": "025.png",
        "flavor": "Un ejemplar joven de dríada, apenas consciente de la fuerza de la naturaleza que corre por sus venas.",
    },
    {
        "id": 26,
        "name": "Dríada Salvaje",
        "rarity": "comun",
        "categorias": ["Naturaleza"],
        "image": "026.png",
        "flavor": "Un dríada salvaje que vaga sin rumbo, atraído instintivamente por cualquier foco de energía de naturaleza.",
    },
    {
        "id": 27,
        "name": "Dríada Errante",
        "rarity": "comun",
        "categorias": ["Naturaleza"],
        "image": "027.png",
        "flavor": "Un dríada errante, expulsado de su manada por no lograr aún controlar su afinidad con la naturaleza.",
    },
    {
        "id": 28,
        "name": "Wyrm Joven",
        "rarity": "comun",
        "categorias": ["Hielo"],
        "image": "028.png",
        "flavor": "Un ejemplar joven de wyrm, apenas consciente de la fuerza del hielo que corre por sus venas.",
    },
    {
        "id": 29,
        "name": "Wyrm Salvaje",
        "rarity": "comun",
        "categorias": ["Hielo"],
        "image": "029.png",
        "flavor": "Un wyrm salvaje que vaga sin rumbo, atraído instintivamente por cualquier foco de energía de hielo.",
    },
    {
        "id": 30,
        "name": "Wyrm Errante",
        "rarity": "comun",
        "categorias": ["Hielo"],
        "image": "030.png",
        "flavor": "Un wyrm errante, expulsado de su manada por no lograr aún controlar su afinidad con el hielo.",
    },
    {
        "id": 31,
        "name": "Salamandra Ancestral",
        "rarity": "rara",
        "categorias": ["Fuego"],
        "image": "031.png",
        "flavor": "Un salamandra ancestral cuya sangre guarda siglos de saber sobre el fuego.",
    },
    {
        "id": 32,
        "name": "Salamandra Feroz",
        "rarity": "rara",
        "categorias": ["Fuego"],
        "image": "032.png",
        "flavor": "Un salamandra feroz que ha sobrevivido incontables batallas gracias a su dominio del fuego.",
    },
    {
        "id": 33,
        "name": "Sirénido Ancestral",
        "rarity": "rara",
        "categorias": ["Agua"],
        "image": "033.png",
        "flavor": "Un sirénido ancestral cuya sangre guarda siglos de saber sobre el agua.",
    },
    {
        "id": 34,
        "name": "Sirénido Feroz",
        "rarity": "rara",
        "categorias": ["Agua"],
        "image": "034.png",
        "flavor": "Un sirénido feroz que ha sobrevivido incontables batallas gracias a su dominio del agua.",
    },
    {
        "id": 35,
        "name": "Coloso Ancestral",
        "rarity": "rara",
        "categorias": ["Tierra"],
        "image": "035.png",
        "flavor": "Un coloso ancestral cuya sangre guarda siglos de saber sobre la tierra.",
    },
    {
        "id": 36,
        "name": "Coloso Feroz",
        "rarity": "rara",
        "categorias": ["Tierra"],
        "image": "036.png",
        "flavor": "Un coloso feroz que ha sobrevivido incontables batallas gracias a su dominio de la tierra.",
    },
    {
        "id": 37,
        "name": "Grifón Ancestral",
        "rarity": "rara",
        "categorias": ["Aire"],
        "image": "037.png",
        "flavor": "Un grifón ancestral cuya sangre guarda siglos de saber sobre el aire.",
    },
    {
        "id": 38,
        "name": "Grifón Feroz",
        "rarity": "rara",
        "categorias": ["Aire"],
        "image": "038.png",
        "flavor": "Un grifón feroz que ha sobrevivido incontables batallas gracias a su dominio del aire.",
    },
    {
        "id": 39,
        "name": "Tronante Ancestral",
        "rarity": "rara",
        "categorias": ["Rayo"],
        "image": "039.png",
        "flavor": "Un tronante ancestral cuya sangre guarda siglos de saber sobre el rayo.",
    },
    {
        "id": 40,
        "name": "Tronante Feroz",
        "rarity": "rara",
        "categorias": ["Rayo"],
        "image": "040.png",
        "flavor": "Un tronante feroz que ha sobrevivido incontables batallas gracias a su dominio del rayo.",
    },
    {
        "id": 41,
        "name": "Espectro Ancestral",
        "rarity": "rara",
        "categorias": ["Sombra"],
        "image": "041.png",
        "flavor": "Un espectro ancestral cuya sangre guarda siglos de saber sobre la sombra.",
    },
    {
        "id": 42,
        "name": "Espectro Feroz",
        "rarity": "rara",
        "categorias": ["Sombra"],
        "image": "042.png",
        "flavor": "Un espectro feroz que ha sobrevivido incontables batallas gracias a su dominio de la sombra.",
    },
    {
        "id": 43,
        "name": "Vigía Ancestral",
        "rarity": "rara",
        "categorias": ["Luz"],
        "image": "043.png",
        "flavor": "Un vigía ancestral cuya sangre guarda siglos de saber sobre la luz.",
    },
    {
        "id": 44,
        "name": "Vigía Feroz",
        "rarity": "rara",
        "categorias": ["Luz"],
        "image": "044.png",
        "flavor": "Un vigía feroz que ha sobrevivido incontables batallas gracias a su dominio de la luz.",
    },
    {
        "id": 45,
        "name": "Autómata Ancestral",
        "rarity": "rara",
        "categorias": ["Arcano"],
        "image": "045.png",
        "flavor": "Un autómata ancestral cuya sangre guarda siglos de saber sobre el arcano.",
    },
    {
        "id": 46,
        "name": "Autómata Feroz",
        "rarity": "rara",
        "categorias": ["Arcano"],
        "image": "046.png",
        "flavor": "Un autómata feroz que ha sobrevivido incontables batallas gracias a su dominio del arcano.",
    },
    {
        "id": 47,
        "name": "Dríada Ancestral",
        "rarity": "rara",
        "categorias": ["Naturaleza"],
        "image": "047.png",
        "flavor": "Un dríada ancestral cuya sangre guarda siglos de saber sobre la naturaleza.",
    },
    {
        "id": 48,
        "name": "Dríada Feroz",
        "rarity": "rara",
        "categorias": ["Naturaleza"],
        "image": "048.png",
        "flavor": "Un dríada feroz que ha sobrevivido incontables batallas gracias a su dominio de la naturaleza.",
    },
    {
        "id": 49,
        "name": "Wyrm Ancestral",
        "rarity": "rara",
        "categorias": ["Hielo"],
        "image": "049.png",
        "flavor": "Un wyrm ancestral cuya sangre guarda siglos de saber sobre el hielo.",
    },
    {
        "id": 50,
        "name": "Wyrm Feroz",
        "rarity": "rara",
        "categorias": ["Hielo"],
        "image": "050.png",
        "flavor": "Un wyrm feroz que ha sobrevivido incontables batallas gracias a su dominio del hielo.",
    },
    {
        "id": 51,
        "name": "Heraldo de las Brasas Eternas",
        "rarity": "epica",
        "categorias": ["Fuego"],
        "image": "051.png",
        "flavor": "Se dice que su sola presencia mantiene encendidas las forjas que nunca se apagan.",
    },
    {
        "id": 52,
        "name": "Forjadora del Volcán Dormido",
        "rarity": "epica",
        "categorias": ["Fuego"],
        "image": "052.png",
        "flavor": "Despierta una vez cada siglo para recordarle al mundo que el fuego nunca muere del todo.",
    },
    {
        "id": 53,
        "name": "Soberana de las Mareas Profundas",
        "rarity": "epica",
        "categorias": ["Agua"],
        "image": "053.png",
        "flavor": "Gobierna las corrientes que ningún mapa ha logrado trazar.",
    },
    {
        "id": 54,
        "name": "Custodio de la Raíz del Mundo",
        "rarity": "epica",
        "categorias": ["Tierra"],
        "image": "054.png",
        "flavor": "Sostiene, literalmente, el peso de todo lo que crece sobre la tierra.",
    },
    {
        "id": 55,
        "name": "Tejedora de Vientos Perdidos",
        "rarity": "epica",
        "categorias": ["Aire"],
        "image": "055.png",
        "flavor": "Reúne los suspiros olvidados del mundo y los convierte en tormentas.",
    },
    {
        "id": 56,
        "name": "Heraldo de la Tormenta Eterna",
        "rarity": "epica",
        "categorias": ["Rayo"],
        "image": "056.png",
        "flavor": "Anuncia su llegada un instante antes de que el cielo se rompa en luz.",
    },
    {
        "id": 57,
        "name": "Centinela del Trueno Quebrado",
        "rarity": "epica",
        "categorias": ["Rayo"],
        "image": "057.png",
        "flavor": "Nació del eco de una tormenta que jamás terminó de caer.",
    },
    {
        "id": 58,
        "name": "Susurro de la Medianoche Eterna",
        "rarity": "epica",
        "categorias": ["Sombra"],
        "image": "058.png",
        "flavor": "Habla solo una vez por visita, y siempre dice la verdad que nadie quiere oír.",
    },
    {
        "id": 59,
        "name": "Guardiana del Velo Roto",
        "rarity": "epica",
        "categorias": ["Sombra"],
        "image": "059.png",
        "flavor": "Vigila la grieta entre lo que existe y lo que casi existió.",
    },
    {
        "id": 60,
        "name": "Portadora del Alba Inquebrantable",
        "rarity": "epica",
        "categorias": ["Luz"],
        "image": "060.png",
        "flavor": "Ninguna oscuridad ha logrado retrasar su amanecer.",
    },
    {
        "id": 61,
        "name": "Archivista de los Sellos Olvidados",
        "rarity": "epica",
        "categorias": ["Arcano"],
        "image": "061.png",
        "flavor": "Conserva fórmulas que el mundo decidió que era mejor olvidar.",
    },
    {
        "id": 62,
        "name": "Tejedor de Paradojas",
        "rarity": "epica",
        "categorias": ["Arcano"],
        "image": "062.png",
        "flavor": "Construye preguntas que no tienen respuesta a propósito.",
    },
    {
        "id": 63,
        "name": "Madre de la Espesura Silente",
        "rarity": "epica",
        "categorias": ["Naturaleza"],
        "image": "063.png",
        "flavor": "Donde ella camina, el bosque vuelve a crecer en una sola noche.",
    },
    {
        "id": 64,
        "name": "Monarca del Glaciar sin Nombre",
        "rarity": "epica",
        "categorias": ["Hielo"],
        "image": "064.png",
        "flavor": "Su trono se derrite un milímetro por siglo, y aún le sobra tiempo.",
    },
    {
        "id": 65,
        "name": "Aurelion, el Forjador del Alba",
        "rarity": "legendaria",
        "categorias": ["Luz"],
        "image": "065.png",
        "flavor": "Se dice que cada amanecer es, en realidad, una de sus obras inconclusas.",
    },
    {
        "id": 66,
        "name": "Nyxara, Devoradora de Estrellas",
        "rarity": "legendaria",
        "categorias": ["Sombra"],
        "image": "066.png",
        "flavor": "Cada constelación que falta en el cielo nocturno fue, alguna vez, su cena.",
    },
    {
        "id": 67,
        "name": "Tharaxis, el Dragón que Fracturó el Cielo",
        "rarity": "legendaria",
        "categorias": ["Rayo"],
        "image": "067.png",
        "flavor": "La grieta permanente sobre las Tierras Altas es la cicatriz de su último vuelo.",
    },
    {
        "id": 68,
        "name": "Ymbrethil, la Raíz Primordial",
        "rarity": "legendaria",
        "categorias": ["Naturaleza"],
        "image": "068.png",
        "flavor": "Todos los bosques del mundo son, según los druidas, una sola de sus ramas.",
    },
    {
        "id": 69,
        "name": "Coraxes, el Último Titán de Piedra",
        "rarity": "legendaria",
        "categorias": ["Tierra"],
        "image": "069.png",
        "flavor": "Duerme bajo la cordillera más alta del reino; las montañas son su respiración.",
    },
    {
        "id": 70,
        "name": "Seraphine del Abismo Helado",
        "rarity": "legendaria",
        "categorias": ["Hielo"],
        "image": "070.png",
        "flavor": "Su canto congela el sonido antes de que termine de escucharse.",
    },
    {
        "id": 71,
        "name": "Vorlag, Señor de las Mareas Negras",
        "rarity": "legendaria",
        "categorias": ["Agua"],
        "image": "071.png",
        "flavor": "Ningún barco que ha visto su sombra bajo el agua ha vuelto a contarlo.",
    },
    {
        "id": 72,
        "name": "Kaelthorne, el Arcanista que Reescribió el Tiempo",
        "rarity": "legendaria",
        "categorias": ["Arcano"],
        "image": "072.png",
        "flavor": "Existen tres versiones de su muerte. Las tres son ciertas.",
    },
]

# --- No edites debajo de esta línea: son solo utilidades de búsqueda ---

RARITY_ORDER = ["comun", "rara", "epica", "legendaria"]

RARITY_LABELS = {
    "comun": "Común",
    "rara": "Rara",
    "epica": "Épica",
    "legendaria": "Legendaria",
}

# Pesos de aparición por rareza dentro de un sobre (deben sumar 1.0)
RARITY_WEIGHTS = {
    "comun": 0.58,
    "rara": 0.28,
    "epica": 0.11,
    "legendaria": 0.03,
}

CARDS_BY_ID = {c["id"]: c for c in CARDS}
CARDS_BY_RARITY = {r: [c for c in CARDS if c["rarity"] == r] for r in RARITY_ORDER}
TOTAL_CARDS = len(CARDS)

# Todas las categorías usadas, en orden alfabético (para armar filtros, etc.)
ALL_CATEGORIES = sorted({cat for c in CARDS for cat in c["categorias"]})
